---
- hosts: "{{ hosts_prompt }}"
  remote_user: cloud-user
  become: yes
  become_method: sudo
  vars_prompt:
    - name: "hosts_prompt"
      prompt: "hostname or host group need to run with Playbook"
      private: no
  tasks:
    - name: Copy the Splunk Forwarder RPM to remote Servers.
      copy:
         src: /home/ansible/splunkforwarder-8.1.1-08187535c166-linux-2.6-x86_64.rpm
         dest: /home/cloud-user
         owner: cloud-user
         group: cloud-user
         mode: 0644
    - name: Import GnuPG Public Key for Splunk package
      rpm_key:
        key: https://git.com/test/syslog/blob/cherif/SplunkPGPKey.pub
        state: present
    - name: Install Splunk Forwarder RPM package on remote servers.
      yum:
        name:
          - python3-pexpect.noarch
          - /home/ansible/splunkforwarder-8.1.1-08187535c166-linux-2.6-x86_64.rpm
        state: present
    - name: Copy the Splunk Forwarder config from your centralized server to remote servers.
      copy:
        src: /home/ansible/inputs.conf
        dest: /opt/splunkforwarder/etc/system/local/
        directory_mode: yes
        owner: splunk
        group: splunk
        mode: 0664
    - name: Start Splunk forwarder service.
      remote_user: ansible
      become: yes
      become_method: sudo
      become_user: splunk
      expect:
        command: /opt/splunkforwarder/bin/splunk start --accept-license
        timeout: 60
        responses:
           (.*)Please enter an administrator username(.*): "admin"
           (.*)Please enter a new password(.*): "redhat@1020"
           (.*)Please confirm new password(.*): "redhat@1020"
    - name: Start Splunk forwarder service on boot.
      remote_user: ansible
      become: yes
      become_method: sudo
      become_user: splunk
      expect:
        command: /opt/splunkforwarder/bin/splunk enable boot-start
        timeout: 60
    - name: Check Splunk forwarder service.
      command:
        /opt/splunkforwarder/bin/splunk status
      register: service_splunk_status
    - name: Report Splunk forwarder Status.
      debug:
         var: service_splunk_status.stdout_lines
...
